name: alacritty
version: '0.4.1-dev'
summary: Modern, GPU accelerated terminal emulator
description: |
  Alacritty is a terminal emulator with a strong focus on simplicity and
  performance. With such a strong focus on performance, included features are
  carefully considered and you can always expect Alacritty to be blazingly fast.
  By making sane choices for defaults, Alacritty requires no additional setup.
  However, it does allow [configuration](#configuration) of many aspects of the
  terminal.

  The software is considered to be at a **beta** level of readiness -- there are
  a few missing features and bugs to be fixed, but it is already used by many as
  a daily driver.
icon: extra/logo/alacritty-term.svg
grade: stable
base: core18
confinement: classic

parts:
  alacritty:
    plugin: rust
    source: .
    build-packages:
      - cmake
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-render0-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
      - libxcb1-dev
      - libgl1-mesa-dev
    override-build: |
      snapcraftctl build
      install -m 755 extra/linux/snap/alacritty.wrapper $SNAPCRAFT_PART_INSTALL/alacritty.wrapper
      install -m 644 extra/linux/alacritty.desktop $SNAPCRAFT_PART_INSTALL/alacritty.desktop
      install -m 644 extra/logo/alacritty-term.svg $SNAPCRAFT_PART_INSTALL/alacritty.svg
      sed -i 's|Icon=.*|Icon=alacritty.svg|g' $SNAPCRAFT_PART_INSTALL/alacritty.desktop
    stage-packages:
      - libfontconfig1
      - libfreetype6
      - libpng16-16
      - libxau6
      - libxcursor1
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
      - libxi6
      - libxrandr2

apps:
  alacritty:
    command: alacritty
    command-chain: [alacritty.wrapper]
    desktop: alacritty.desktop
    extensions: [opengl]
